### ISSUE TITLE
Fail to install using composer

### ISSUE THREAD

**Issue by groyal** [saintsystems/dynamics-sdk-php#1]
I am having trouble installing through composer. 
I get this error: 

I have tried both "saintsystems/dynamics-sdk-php" and  "Microsoft/Dynamics"
Thanks

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package saintsystems/dynamics-sdk-php could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by anderly** [comment]
Hi Greg, apologies for the issue installing. We haven't published this package to composer as some components are in-flux. However, you should be able to install directly from GitHub using the following in your composer.json:

```
"repositories": [{
    "type": "package",
    "package": {
        "version": "dev-master",
        "name": "saintsystems/dynamics-sdk-php",
        "source": {
            "url": "https://github.com/saintsystems/dynamics-sdk-php.git",
            "type": "git",
            "reference": "master"
        }
    }
}],
"require": {
    "saintsystems/dynamics-sdk-php": "dev-master"
},
```

Just a heads up, the namespace of this project will eventually change from Microsoft\Dynamics to SaintSystems\Dynamics or something similar.

Let me know if run into any issues installing using the approach above.

**Comment by groyal** [comment]
thanks, I got it running by downloading it.  Was looking for a way to use composer to integrate with OAUTH2 package TheNetworg/oauth2-azure. So downloaded zip file and added their composer and ran their composer 

> "composer require thenetworg/oauth2-azure"
